# Generated by Django 5.2.8 on 2025-11-21 23:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedor', '0001_initial'),
        ('usuarios', '0005_comerciante_last_login_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='proveedor', to='usuarios.comerciante'),
        ),
    ]
