# Generated by Django 5.2.8 on 2025-11-22 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedor', '0002_alter_proveedor_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='perfiles/', verbose_name='Foto de Perfil Personal'),
        ),
    ]
