# Generated by Django 5.2.8 on 2025-11-22 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedor', '0003_proveedor_foto_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='idioma',
            field=models.CharField(default='es', max_length=5),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='modo_oscuro',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='mostrar_estadisticas',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='notif_email',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='notif_mensajes',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='notif_pedidos',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='perfil_publico',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='zona_horaria',
            field=models.CharField(default='America/Santiago', max_length=50),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='proveedores/fotos/'),
        ),
    ]
