# Generated by Django 5.2.8 on 2025-11-22 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedor', '0004_proveedor_idioma_proveedor_modo_oscuro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoservicio',
            name='categoria',
            field=models.CharField(choices=[('ALIMENTOS', 'Alimentos y Comida'), ('BEBIDAS', 'Bebidas y Licores'), ('ROPA', 'Ropa y Accesorios'), ('HOGAR', 'Artículos para el Hogar'), ('SERVICIOS', 'Servicios Profesionales'), ('OTRO', 'Otro / Varios')], default='OTRO', max_length=50, verbose_name='Categoría del Producto/Servicio'),
        ),
    ]
