# Generated by Django 5.2.5 on 2025-11-16 03:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comentario',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'Comentario', 'verbose_name_plural': 'Comentarios'},
        ),
        migrations.AddField(
            model_name='comerciante',
            name='nivel_actual',
            field=models.CharField(default='Bronce', max_length=50, verbose_name='Nivel de Beneficios'),
        ),
        migrations.AddField(
            model_name='comerciante',
            name='puntos',
            field=models.IntegerField(default=0, verbose_name='Puntos Acumulados'),
        ),
        migrations.CreateModel(
            name='Beneficio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('descripcion', models.TextField()),
                ('tipo', models.CharField(choices=[('SORTEO', 'Sorteo'), ('DESCUENTO', 'Descuento'), ('PROMOCION', 'Promoción'), ('CONCURSO', 'Concurso'), ('GENERAL', 'General')], max_length=20)),
                ('estado', models.CharField(default='ACTIVO', max_length=30)),
                ('vence', models.DateField(blank=True, null=True)),
                ('imagen_url', models.URLField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Subido por')),
            ],
            options={
                'verbose_name': 'Beneficio y Promoción',
                'verbose_name_plural': 'Beneficios y Promociones',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
