# Generated by Django 5.2.5 on 2025-11-16 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_comentario_options_comerciante_nivel_actual_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beneficio',
            name='imagen_url',
        ),
        migrations.RemoveField(
            model_name='beneficio',
            name='tipo',
        ),
        migrations.AddField(
            model_name='beneficio',
            name='categoria',
            field=models.CharField(choices=[('DESCUENTO', 'Descuento y Ofertas'), ('SORTEO', 'Sorteos y Rifas'), ('CAPACITACION', 'Capacitación y Cursos'), ('ACCESO', 'Acceso Exclusivo'), ('EVENTO', 'Eventos Especiales')], default='DESCUENTO', max_length=50, verbose_name='Categoría'),
        ),
        migrations.AddField(
            model_name='beneficio',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='beneficios_fotos/', verbose_name='Imagen'),
        ),
        migrations.AddField(
            model_name='beneficio',
            name='puntos_requeridos',
            field=models.IntegerField(default=0, verbose_name='Puntos Requeridos'),
        ),
        migrations.AlterField(
            model_name='beneficio',
            name='descripcion',
            field=models.TextField(verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='beneficio',
            name='estado',
            field=models.CharField(choices=[('ACTIVO', 'Activo'), ('TERMINADO', 'Terminado'), ('BENEFICIO_ACTIVO', 'Beneficio Reclamado')], default='ACTIVO', max_length=30),
        ),
        migrations.AlterField(
            model_name='beneficio',
            name='titulo',
            field=models.CharField(max_length=200, verbose_name='Título del Beneficio'),
        ),
        migrations.AlterField(
            model_name='beneficio',
            name='vence',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Vencimiento'),
        ),
        migrations.AlterField(
            model_name='comerciante',
            name='nivel_actual',
            field=models.CharField(choices=[('BRONCE', 'Bronce'), ('PLATA', 'Plata'), ('ORO', 'Oro'), ('DIAMANTE', 'Diamante')], default='BRONCE', max_length=50, verbose_name='Nivel de Beneficios'),
        ),
    ]
