# Generated by Django 5.2.5 on 2025-11-14 23:17

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='comerciante',
            name='foto_perfil',
            field=models.ImageField(blank=True, default='usuarios/img/default_profile.png', null=True, upload_to='perfiles/'),
        ),
        migrations.AddField(
            model_name='comerciante',
            name='intereses',
            field=models.CharField(blank=True, default='', help_text='Códigos de intereses separados por coma.', max_length=512),
        ),
        migrations.AddField(
            model_name='comerciante',
            name='nombre_negocio',
            field=models.CharField(blank=True, default='Mi Negocio Local', max_length=100),
        ),
        migrations.AlterField(
            model_name='comerciante',
            name='comuna',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='comerciante',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='comerciante',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='comerciante',
            name='nombre_apellido',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='comerciante',
            name='password_hash',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='comerciante',
            name='relacion_negocio',
            field=models.CharField(choices=[('DUEÑO', 'Dueño/a'), ('ADMIN', 'Administrador/a'), ('EMPLEADO', 'Empleado/a clave'), ('FAMILIAR', 'Familiar a cargo')], max_length=10),
        ),
        migrations.AlterField(
            model_name='comerciante',
            name='tipo_negocio',
            field=models.CharField(choices=[('ALMACEN', 'Almacén de Barrio'), ('MINIMARKET', 'Minimarket'), ('BOTILLERIA', 'Botillería'), ('PANADERIA', 'Panadería/Pastelería'), ('FERIA', 'Feria Libre'), ('KIOSCO', 'Kiosco'), ('FOODTRUCK', 'Food Truck/Carro de Comida')], max_length=20),
        ),
        migrations.AlterField(
            model_name='comerciante',
            name='ultima_conexion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='comerciante',
            name='whatsapp',
            field=models.CharField(blank=True, help_text='Formato: +569XXXXXXXX', max_length=12, null=True, validators=[django.core.validators.RegexValidator(message="El formato debe ser '+569XXXXXXXX'.", regex='^\\+569\\d{8}$')]),
        ),
        migrations.AlterField(
            model_name='post',
            name='imagen_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL de Imagen/Link de Archivo Subido'),
        ),
    ]
