# Generated by Django 5.2.8 on 2025-11-18 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_remove_beneficio_imagen_url_remove_beneficio_tipo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comerciante',
            name='nivel_actual',
            field=models.CharField(choices=[('BRONCE', 'Bronce'), ('PLATA', 'Plata'), ('ORO', 'Oro'), ('PLATINO', 'Platino'), ('DIAMANTE', 'Diamante')], default='BRONCE', max_length=50, verbose_name='Nivel de Beneficios'),
        ),
    ]
