# Generated by Django 5.2.8 on 2025-11-21 18:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_alter_comerciante_nivel_actual'),
    ]

    operations = [
        migrations.AddField(
            model_name='comerciante',
            name='last_login',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='comerciante',
            name='ultima_conexion',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
